// import bcrypt from 'bcryptjs';

const data = {
    // users: [
    //     {
    //         name: 'John Brzenk',
    //         email: 'admin@example.com',
    //         password: bcrypt.hashSync('qwerqwer'),
    //         isAdmin: true,
    //     },
    //     {
    //         name: 'Bob',
    //         email: 'user@example.com',
    //         password: bcrypt.hashSync('qwerqwer'),
    //         isAdmin: false,
    //     },
    // ],
    products: [
        {
            name: 'Tai nghe chụp tai không dây bluetooth STN28 màu sắc cute,âm thanh ấm bass mạnh- Phụ Kiện 123',
            slug: 'tai-nghe-chup-tai-khong-day-bluetooth-stn28',
            category: 'Gaming',
            image: '/images/headphone.jpg',
            price: 70,
            brand: 'Phụ kiện 123',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'Thiết kế thông minh: Có khả năng gấp gọn lại cũng như kéo dãn ra để vừa mọi cỡ đầu. Chất liệu cao cấp: Phần khung được làm bằng nhựa cao cấp cực bền và không gây mùi khó chịu. Kết nối đa dạng: Kết nối không dây bằng Bluetooth cho phạm vi kết nối lên tới 10m. Hỗ trợ mic đàm thoại khả năng tương thích với các smartphone là 100%.',
            isFeatured: true,
            banner: '/images/headphone.jpg',
        },
        {
            name: 'Loa xách tay bluetooth speaker H.S.L.H Âm thanh đỉnh cao BT 201 Bảo Hành Chính Hãng 6 tháng 1 đổi 1',
            slug: 'loa-xach-tay-bluetooth-speaker-hslh',
            category: 'Gaming',
            image: '/images/speaker2.jpg',
            price: 80,
            brand: 'Sony',
            rating: 3.2,
            numReviews: 10,
            countInStock: 20,
            description: 'Loa xách tay bluetooth speaker H.S.L.H Âm thanh đỉnh cao. Mẫu loa mới được giới thiệu vào cuối tháng 03/2018, với thiết kế bắt mắt cùng công suất lớn, loa được dùng để nghe nhạc rất tốt, loa có thêm tay xách nên cũng tiện dùng trong những chuyến đi xa ( đi phượt, dã ngoài, picnic...)',
            isFeatured: true,
            banner: '/images/speaker2.jpg',
        },
        {
            name: 'Loa bluetooth đồng hồ G5, loa mini không dây nghe nhạc làm đèn ngủ màn hình soi gương',
            slug: 'loa-bluetooth-dong-ho-g5',
            category: 'Gaming',
            image: '/images/clock.jpg',
            price: 90,
            brand: 'Raymond',
            rating: 4.5,
            numReviews: 3,
            countInStock: 20,
            description: 'Loa bluetooth đồng hồ G5, loa mini không dây Clock seaker D88 nghe nhạc. Chú ý: loa có công suất 3w 1 bên là loa còn một bên là màng chắn âm bass, mặt kính có giấy bóng bọc bên ngoài, khi sử dụng quý khách nên bóc giấy bóng ra. Sản phẩm có 2 phiên bản - phiên bản G5 nội địa và phiên bản Clock Speaker D88 Châu âu (tiếng anh)',
        },
        {
            name: 'Bàn Phím CƠ ZIYOU K3 Luxury Cao Cấp, Phím Gõ Êm Sử Dụng Trục Cơ Red Switch, Led 16,5 Triệu Màu 10 Chế Độ, Bảo Hành 12t',
            slug: 'ban-phim-co-ziyou-k3',
            category: 'Gaming',
            image: '/images/keyboard.jpg',
            price: 90,
            brand: 'Oliver',
            rating: 2.9,
            numReviews: 13,
            countInStock: 20,
            description: 'Bàn phím cơ sử dụng switch treo cho độ nảy, độ đàn hồi và độ nhạy cực tốt, Switch red tuổi thọ tốt lên đến 60 triệu lượt nhấn, đảm bảo bàn phím bền bỉ đồng hành cùng bạn trong suốt thời gian dài. Dù là bàn phím gaming nhưng K3 Luxury lại có thiết kế khá đơn giản, trang nhã để bạn dễ dàng đặt nó trên bàn làm việc gia đình hoặc cả ở văn phòng, hay mang theo sử dụng khi ra ngoài',
        },
        {
            name: 'Loa Bluetooth D004B giá chỉ 109K / 1C giá tốt nhất thị trườngFit Pants',
            slug: 'loa-bluetooth-d004b',
            category: 'Gaming',
            image: '/images/speaker.jpg',
            price: 95,
            brand: 'Zara',
            rating: 3.5,
            numReviews: 7,
            countInStock: 20,
            description: 'Loa bluetooth hỗ trợ Kết nối không dây Bluetooth 5.0 (khoảng cách 10m). Thời gian sạc : khoảng 1,5 giờ. Thời gian làm việc : 4 giờ tuỳ Volume và khoảng cách',
        },
        {
            name: 'Chuột không dây GOOJODOQ Bluetooth 2.4Ghz 2 trong 1 chất lượng cao for ipad',
            slug: 'chuot-khong-day-goojodoq',
            category: 'Learning',
            image: '/images/mouse.jpg',
            price: 75,
            brand: 'Erilles',
            rating: 2.4,
            numReviews: 14,
            countInStock: 20,
            description: 'Các tính năng và thông số kỹ thuật:\n1, Chế độ kép: Bluetooth và 2.4G không dây, công nghệ mới nhất.\n2, Phím tắt tiếng: phím tắt tiếng nâng cao, nhấp chuột im lặng\n3, Theo dõi chính xác: Độ chính xác định vị IC chuyên dụng',
        },
    ],
};

export default data;
