version: '3'

services:
  #  start Redis, and ensure that data is stored to a mounted volume
  redis:
    image: 'redis:alpine'
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ../db-data/redis/:/data

  #  start Postgres, and ensure that data is stored to a mounted volume
  postgres:
    image: 'postgres:14.0'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerqwer
      POSTGRES_DB: cycir
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

  #  start mailhog
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - "1025:1025"
      - "8025:8025"

  # ipe websocket
  ipe:
    image: 'tsawler/ipe:latest'
    build:
      context: ./../ipe
      dockerfile: ./ipe.dockerfile
    restart: always
    ports:
      - "4001:4001"
    deploy:
      mode: replicated

  # backend-service:
  #   build:
  #     context: ./../cmd/api
  #     dockerfile: ./backend-service.dockerfile
  #   restart: always
  #   ports:
  #     - "8080:80"
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #   environment:
  #     DB_DSN: "host=localhost port=5432 user=postgres password=qwerqwer dbname=cycir sslmode=disable timezone=UTC connect_timeout=5"
  #     ES_ADDRESS: "http://localhost:9200"
  #     ES_USERNAME: "elastic"
  #     ES_PASSWORD: "E08_6Tmn3QyzhI4XLxyR"
  #     ES_INDEX: "cycir"
  #     PUSHER_HOST: "localhost"
  #     PUSHER_PORT: "4001"
  #     PUSHER_SECRET: "123abc"
  #     PUSHER_KEY: "abc123"
  #     PUSHER_SECURE: "disable"
  #     PUSHER_APP: "1"
  #     IN_PRODUCTION: "disable"
  #     DOMAIN: "localhost"

  frontend:
    build:
      context: ./../cmd/web
      dockerfile: ./frontend-service.dockerfile
    restart: always
    ports:
      - "8081:80"
    deploy:
      mode: replicated
    environment:
      DB_DSN: "host=localhost port=5432 user=postgres password=qwerqwer dbname=cycir sslmode=disable timezone=UTC connect_timeout=5"
      REDIS_HOST: "localhost:6379"
      REDIS_PREFIX: "cycir"
      PUSHER_HOST: "localhost"
      PUSHER_PORT: "4001"
      PUSHER_SECRET: "178d525bdf162c739803"
      PUSHER_KEY: "278d525bdf162c739803"
      PUSHER_SECURE: "disable"
      PUSHER_APP: "1"
      IN_PRODUCTION: "disable"
      DOMAIN: "localhost"
  
  caddy: 
    image: virmos/micro-caddy:1.0.0
    deploy: 
      mode: replicated
      replicas: 1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy_data:/data
      - ./caddy_config:/config
